name: Trigger auto deployment for budget-planner-monthly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/budget-planner-monthly-AutoDeployTrigger-408a229e-1b8e-4d80-a383-356a41d6d37d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BUDGETPLANNERMONTHLY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUDGETPLANNERMONTHLY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUDGETPLANNERMONTHLY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: budgetplannerregistry.azurecr.io
          registryUsername: ${{ secrets.BUDGETPLANNERMONTHLY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUDGETPLANNERMONTHLY_REGISTRY_PASSWORD }}
          containerAppName: budget-planner-monthly
          resourceGroup: budget-planner-resource
          imageToBuild: budgetplannerregistry.azurecr.io/budget-planner-monthly:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


